# ENV1 / ENV2
environment: ENV1

# web / mobile / api
framework: mobile

web:
  grid: false
  debug: false
  headless: false
mobile:
# android / ios
  system: android
  debug: false
api:
  debug: false