name: API tests (Playwright framework)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'   # 07:00 PL

permissions:
  contents: write

concurrency:
  group: api-tests-2
  cancel-in-progress: true

jobs:
  api-tests-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run API tests
        run: |
          mvn -pl java-playwright-test-automation-framework test \
          -Dsurefire.suiteXmlFiles=src/test/resources/testSuites/api/PET_STORE.xml \
          -Denvironment=ENV1 -Dplatform=api -Dapi.debug=false

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api-2
          path: java-playwright-test-automation-framework/allure-results
